
from os import environ
class BaseConfig(object):
    PROJECT_NAME = 'async_flask'
    _SQLALCHEMY_DATABASE_NAME = environ.get('DATABASE', False) or PROJECT_NAME.lower()
    _SQLALCHEMY_DATABASE_HOST = environ.get('DB_HOST')
    _SQLALCHEMY_DATABASE_USERNAME = environ.get('DB_USER')
    _SQLALCHEMY_DATABASE_PASSWORD = environ.get('DB_PASS')
    _SQLALCHEMY_DATABASE_PORT = environ.get('DB_PORT')
    SQLALCHEMY_DATABASE_URI = f'postgresql+asyncpg://{_SQLALCHEMY_DATABASE_USERNAME}:{_SQLALCHEMY_DATABASE_PASSWORD}@{_SQLALCHEMY_DATABASE_HOST}:{_SQLALCHEMY_DATABASE_PORT}/{_SQLALCHEMY_DATABASE_NAME}'
    SQLALCHEMY_TRACK_MODIFICATIONS  = False
    SQLALCHEMY_ECHO = False